apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "argocd-demo.fullname" . }}-config
  labels:
    {{- include "argocd-demo.labels" . | nindent 4 }}
data:
  APP_VERSION: {{ .Values.app.version | quote }}
  APP_ENVIRONMENT: {{ .Values.app.environment | quote }}

